### ISSUE TITLE
a little problem about preronnie

### ISSUE THREAD

**Issue by ghost** [nasa/CFL3D#21]
In `usrint.F` and `termn8.F` in ronnie directory, inclusion of `mpif.h` is:
```
#if defined DIST_MPI
     include 'mpif.h'
#endif
```
which is different from `source\cfl3d\dist\termn8.F`:
```
#if defined DIST_MPI
#     include "mpif.h"
#endif
```

It causes some trouble when mingw-w64 gfortran is used with MS-MPI on windows platform, following  [TUTORIAL: Adapting MS-MPI for MinGW64](https://github.com/dev-cafe/autocmake/issues/85#issue-102874399) .

According to https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vna1/index.html, it can be explained as:

> Files included by the preprocessor #include directive can contain #defines and the like; files included with the compiler INCLUDE statement must contain **only** FORTRAN statements.

**Comment by crumsey** [comment]
Fix has been committed
