### ISSUE TITLE
makefile:85: recipe for target 'cfl3d_mpi' failed

### ISSUE THREAD

**Issue by MaganS** [nasa/CFL3D#23]
I am installing CFL3D on CrayXC40, after editing the machine specific section in Makefile in the build directory for cray Fortran compiler. I am getting following errors in the building cfl3d_mpi.
ln: failed to create symbolic link './xe.o': File exists
ln: failed to create symbolic link './xlim.o': File exists
ln: failed to create symbolic link './xmukin.o': File exists
ln: failed to create symbolic link './xtbatb.o': File exists
ln: failed to create symbolic link './xupdt.o': File exists
ln: failed to create symbolic link './xyzintr.o': File exists
makefile:85: recipe for target 'cfl3d_mpi' failed
make[1]: [cfl3d_mpi] Error 1 (ignored)
ftn -DDIST_MPI -DDBLE_PRECSN -DP3D_SINGLE -DLINUX -DINTEL -DDBLE_PRECSN   -o cfl3d_mpi *.o  
cputim.o: In function `cputim_':
/mnt/lustre/ase3/asemagan/CFL3D_RANSC/CFL3D-master/source/cfl3d/dist/cputim.F:159: undefined reference to `etime_'
/mnt/lustre/ase3/asemagan/CFL3D_RANSC/CFL3D-master/source/cfl3d/dist/cputim.F:160: undefined reference to `itime_'
makefile:85: recipe for target 'cfl3d_mpi' failed
make[1]: *** [cfl3d_mpi] Error 1
make[1]: Leaving directory '/mnt/lustre/ase3/asemagan/CFL3D_RANSC/CFL3D-master/build/cfl/mpi'
makefile:396: recipe for target 'Zmpi' failed
make: *** [Zmpi] Error 2
![screenshot from 2019-01-09 23-13-52](https://user-images.githubusercontent.com/44393219/50917730-4fd2a200-1464-11e9-8663-7a5c1fb58f03.png)

Please give some advice.

**Comment by yagizb** [comment]
How did you solve it?

**Comment by sundae91** [comment]
恩，已经收到啦~                                                               孙迪
