### ISSUE TITLE
Is the Intel Compiler Flag '' FTN='mpiifort' a typo?

### ISSUE THREAD

**Issue by acdefrei** [nasa/CFL3D#25]
Is the Intel Compiler Flag '' FTN='mpiifort' a typo in the install file?

**Comment by crumsey** [comment]
Probably not.  However, note that the Install file is old old old.  It comes with no assurance or guarantees.  You may need to modify it for your own use.  For me, personally, I use Install as is, then I hand-edit the resulting makefile.  For example, for my linux machine, the first part of makefile is edited to look like the following:

# *************** COMPILER FLAG DEFINITIONS (MACHINE SPECIFIC) ***************
#                 (CURRENT DEFINITIONS FOR LINUX ARCHITECTURE)

FFLAG        = -axAVX -xSSE4.2 -O2 -w -ip -fno-alias -traceback -module /yourlocation/CFL3D/build/$(CFLLIBSD)
FFLAG_SPEC   = -axAVX -xSSE4.2 -O2 -w -ip -fno-alias -traceback -module /yourlocation/CFL3D/build/$(CFLLIBSD)
PREC         = -r8
PREC_MPI     = -DDBLE_PRECSN
LFLAG        = -z muldefs -xHost -traceback -fpe0
LLIBS        =
LLIBS_SEQ    =
MPI_INCDIR   =
CGNS_INCDIR  =
CPP          = cpp
CPPFLAG      = -P
CPPOPT       =  $(MPI_INCDIR) -DDIST_MPI $(PREC_MPI)
CPPOPT_SP    = -DP3D_SINGLE -DLINUX -DINTEL -DNOREDIRECT $(PREC_MPI) $(CGNS_INCDIR)
CPPOPT_CMPLX = -DCMPLX
FTN          = mpif90
CC           = mpicc
CFLAG        =
AROPT        = rusc
RANLIB       = true
INLINE       =

**Comment by acdefrei** [comment]
Thanks!
